version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: edu_stack_sandbox_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-student}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-student}
      POSTGRES_DB: ${POSTGRES_DB:-skola_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: edu_stack_sandbox_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  backend:
    image: node:22-alpine
    container_name: edu_stack_sandbox_backend
    restart: always
    working_dir: /app
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npx prisma generate && npm run start:dev"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER:-student}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-student}
      POSTGRES_DB: ${POSTGRES_DB:-skola_db}
      DATABASE_URL: postgresql://${POSTGRES_USER:-student}:${POSTGRES_PASSWORD:-student}@postgres:5432/${POSTGRES_DB:-skola_db}
    depends_on:
      - postgres

volumes:
  postgres_data:
