import type { INestApplication } from '@nestjs/common';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { ErrorResponseDto } from './common/dto/error-response.dto';
import {
  LoginDto,
  LoginResponseDto,
  AcceptInviteDto,
  ForgotPasswordDto,
  ResetPasswordDto,
  SelectSchoolResponseDto,
  UserProfileDto,
  SchoolListItemDto,
  SsoOptionDto,
  CreateGradeDto,
  UpdateGradeDto,
  GradeResponseDto,
  RecordAttendanceDto,
  AttendanceRecordItemDto,
  CreateScheduleEventDto,
  CreateSubstitutionDto,
  CreateConversationDto,
  SendMessageDto,
  CreateBulletinPostDto,
  CreatePollDto,
  CreateCalendarEventDto,
  UpsertClassbookEntryDto,
  CreateClassroomDto,
  CreateSubjectDto,
  CreateRoomDto,
  InviteSchoolUserDto,
  SuccessResponseDto,
  CountResponseDto,
  ToggleResponseDto,
} from './common/dto/api.dto';
import {
  ClassroomResponseDto,
  SubjectResponseDto,
  RoomResponseDto,
  BuildingResponseDto,
  SchoolEventResponseDto,
  SchoolUserResponseDto,
  StudentFamilyResponseDto,
  AuditLogEntryDto,
  SchoolSettingsResponseDto,
  AcademicYearResponseDto,
  GradeLevelResponseDto,
  SubjectInstanceResponseDto,
  TeacherWorkloadResponseDto,
  CurriculumVersionResponseDto,
  CurriculumEntryResponseDto,
  CompetencyResponseDto,
  SemesterResponseDto,
  ThematicPlanResponseDto,
  TeachingMaterialResponseDto,
  LessonPlanResponseDto,
  EnrollmentResponseDto,
  ScheduleEventResponseDto,
  ScheduleMatrixResponseDto,
  SubstitutionResponseDto,
  CollisionResultDto,
  SnapshotResponseDto,
  RecurringEventResponseDto,
  AttendanceRecordResponseDto,
  ExcuseResponseDto,
  AttendanceStatsResponseDto,
  UnexcusedAlertDto,
  ConversationResponseDto,
  MessageResponseDto,
  NotificationResponseDto,
  RecipientResponseDto,
  BulletinPostResponseDto,
  PollResponseDto,
  CommunityEventResponseDto,
  ClassbookEntryResponseDto,
  ReportCardResponseDto,
  GradingTypeResponseDto,
  BehaviorGradeResponseDto,
  CompetencyGradeResponseDto,
  MeasureResponseDto,
  GradeHistoryEntryDto,
  CommissionExamResponseDto,
  GradingDeadlineResponseDto,
  SchoolDashboardResponseDto,
  SharedRoomResponseDto,
  SsoIdentityResponseDto,
  UploadResultDto,
  ImportResultDto,
  StudentDataResponseDto,
  ChildDashboardResponseDto,
  ParentChildResponseDto,
  TeacherClassResponseDto,
  SystemDashboardResponseDto,
  SchoolResponseDto,
  SsoConfigResponseDto,
  AiConfigResponseDto,
  AiUsageResponseDto,
  AiTextResponseDto,
  BackupResponseDto,
  HealthCheckResponseDto,
  MetricsResponseDto,
  RvpUploadResponseDto,
  CompetencyMatrixResponseDto,
  CurriculumDiffResponseDto,
  ScheduleDiffResponseDto,
  GenerateScheduleResultDto,
  GdprDataResponseDto,
  InitStatusResponseDto,
  ReportStatsResponseDto,
  RegistryClassroomResponseDto,
  SystemSettingsResponseDto,
  PaginatedUsersResponseDto,
} from './common/dto/response.dto';

const TAGS: Array<[string, string]> = [
  ['auth', 'Autentizace a pozvánky'],
  ['init', 'Inicializace systému'],
  ['student', 'Studentský modul'],
  ['parent', 'Rodičovský modul'],
  ['teacher', 'Učitelský modul'],
  ['deputy', 'Zástupce školy – administrativa a kurikulum'],
  ['principal', 'Ředitel – audit a vedení'],
  ['system', 'Systémová administrace'],
  ['users', 'Správa uživatelů a pozvánek'],
  ['grading', 'Klasifikace a hodnocení'],
  ['schedule', 'Rozvrh a suplování'],
  ['messaging', 'Komunikace a notifikace'],
  ['attendance', 'Docházka'],
  ['community', 'Komunita – nástěnka, ankety, události'],
  ['classbook', 'Třídní kniha'],
  ['ai', 'AI funkce – generování, analýza, moderace'],
  ['registry', 'Matrika – MŠMT registry'],
  ['export', 'Export dat – CSV/XML/JSON'],
  ['reports', 'Reporty – statistiky, výkazy ČŠI/MŠMT'],
  ['gdpr', 'GDPR – export a smazání osobních dat'],
];

const EXTRA_MODELS = [
  ErrorResponseDto,
  // api.dto.ts (request + generic)
  LoginDto,
  LoginResponseDto,
  AcceptInviteDto,
  ForgotPasswordDto,
  ResetPasswordDto,
  SelectSchoolResponseDto,
  UserProfileDto,
  SchoolListItemDto,
  SsoOptionDto,
  CreateGradeDto,
  UpdateGradeDto,
  GradeResponseDto,
  RecordAttendanceDto,
  AttendanceRecordItemDto,
  CreateScheduleEventDto,
  CreateSubstitutionDto,
  CreateConversationDto,
  SendMessageDto,
  CreateBulletinPostDto,
  CreatePollDto,
  CreateCalendarEventDto,
  UpsertClassbookEntryDto,
  CreateClassroomDto,
  CreateSubjectDto,
  CreateRoomDto,
  InviteSchoolUserDto,
  SuccessResponseDto,
  CountResponseDto,
  ToggleResponseDto,
  // response.dto.ts (entity responses)
  ClassroomResponseDto,
  SubjectResponseDto,
  RoomResponseDto,
  BuildingResponseDto,
  SchoolEventResponseDto,
  SchoolUserResponseDto,
  StudentFamilyResponseDto,
  AuditLogEntryDto,
  SchoolSettingsResponseDto,
  AcademicYearResponseDto,
  GradeLevelResponseDto,
  SubjectInstanceResponseDto,
  TeacherWorkloadResponseDto,
  CurriculumVersionResponseDto,
  CurriculumEntryResponseDto,
  CompetencyResponseDto,
  SemesterResponseDto,
  ThematicPlanResponseDto,
  TeachingMaterialResponseDto,
  LessonPlanResponseDto,
  EnrollmentResponseDto,
  ScheduleEventResponseDto,
  ScheduleMatrixResponseDto,
  SubstitutionResponseDto,
  CollisionResultDto,
  SnapshotResponseDto,
  RecurringEventResponseDto,
  AttendanceRecordResponseDto,
  ExcuseResponseDto,
  AttendanceStatsResponseDto,
  UnexcusedAlertDto,
  ConversationResponseDto,
  MessageResponseDto,
  NotificationResponseDto,
  RecipientResponseDto,
  BulletinPostResponseDto,
  PollResponseDto,
  CommunityEventResponseDto,
  ClassbookEntryResponseDto,
  ReportCardResponseDto,
  GradingTypeResponseDto,
  BehaviorGradeResponseDto,
  CompetencyGradeResponseDto,
  MeasureResponseDto,
  GradeHistoryEntryDto,
  CommissionExamResponseDto,
  GradingDeadlineResponseDto,
  SchoolDashboardResponseDto,
  SharedRoomResponseDto,
  SsoIdentityResponseDto,
  UploadResultDto,
  ImportResultDto,
  StudentDataResponseDto,
  ChildDashboardResponseDto,
  ParentChildResponseDto,
  TeacherClassResponseDto,
  SystemDashboardResponseDto,
  SchoolResponseDto,
  SsoConfigResponseDto,
  AiConfigResponseDto,
  AiUsageResponseDto,
  AiTextResponseDto,
  BackupResponseDto,
  HealthCheckResponseDto,
  MetricsResponseDto,
  RvpUploadResponseDto,
  CompetencyMatrixResponseDto,
  CurriculumDiffResponseDto,
  ScheduleDiffResponseDto,
  GenerateScheduleResultDto,
  GdprDataResponseDto,
  InitStatusResponseDto,
  ReportStatsResponseDto,
  RegistryClassroomResponseDto,
  SystemSettingsResponseDto,
  PaginatedUsersResponseDto,
];

/**
 * Mount Swagger/OpenAPI documentation at `/api/docs`. No-op in production.
 */
export function setupSwagger(app: INestApplication): void {
  if (process.env.NODE_ENV === 'production') return;

  const builder = new DocumentBuilder()
    .setTitle('EduStack IS API')
    .setDescription('Školní informační systém – REST API dokumentace')
    .setVersion('1.0')
    .addBearerAuth(
      { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
      'JWT-auth',
    );
  for (const [name, desc] of TAGS) {
    builder.addTag(name, desc);
  }

  const document = SwaggerModule.createDocument(app, builder.build(), {
    extraModels: EXTRA_MODELS,
  });
  SwaggerModule.setup('/api/docs', app, document);
}
